---
language: ruby
cache: bundler
os:
  - osx
  - linux
osx_image:
  - xcode12
  - xcode11
dist:
  - precise
  - trusty
  - xenial
  - bionic
rvm:
  - 2.7.2
  - 3.0.0
before_install: gem install bundler -v 2.2.3
